# NUC700 series audio
snd-soc-nuc700-pcm-objs := nuc700-pcm.o
snd-soc-nuc700-ac97-objs := nuc700-ac97.o

obj-$(CONFIG_SND_SOC_NUC700) += snd-soc-nuc700-pcm.o
obj-$(CONFIG_SND_SOC_NUC700_AC97) += snd-soc-nuc700-ac97.o

# Boards
snd-soc-nuc700-audio-objs := nuc700-audio.o

obj-$(CONFIG_SND_SOC_NUC700EVB) += snd-soc-nuc700-audio.o
